"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class joint_keyposes(object):
    __slots__ = ["dof_pos", "keyposes"]

    def __init__(self):
        self.dof_pos = [ 0.0 for dim0 in range(23) ]
        self.keyposes = [ 0.0 for dim0 in range(36) ]

    def encode(self):
        buf = BytesIO()
        buf.write(joint_keyposes._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>23d', *self.dof_pos[:23]))
        buf.write(struct.pack('>36d', *self.keyposes[:36]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != joint_keyposes._get_packed_fingerprint():
            raise ValueError("Decode error")
        return joint_keyposes._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = joint_keyposes()
        self.dof_pos = struct.unpack('>23d', buf.read(184))
        self.keyposes = struct.unpack('>36d', buf.read(288))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if joint_keyposes in parents: return 0
        tmphash = (0xb0b64c4a99d2c4bc) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if joint_keyposes._packed_fingerprint is None:
            joint_keyposes._packed_fingerprint = struct.pack(">Q", joint_keyposes._get_hash_recursive([]))
        return joint_keyposes._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

