"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class joint_angles(object):
    __slots__ = ["dof_pos"]

    def __init__(self):
        self.dof_pos = [ 0.0 for dim0 in range(23) ]

    def encode(self):
        buf = BytesIO()
        buf.write(joint_angles._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>23d', *self.dof_pos[:23]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != joint_angles._get_packed_fingerprint():
            raise ValueError("Decode error")
        return joint_angles._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = joint_angles()
        self.dof_pos = struct.unpack('>23d', buf.read(184))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if joint_angles in parents: return 0
        tmphash = (0x96472cc72a5cceb8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if joint_angles._packed_fingerprint is None:
            joint_angles._packed_fingerprint = struct.pack(">Q", joint_angles._get_hash_recursive([]))
        return joint_angles._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

